name: docker

on:
  push:
    branches: ['master']

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: https://github.com/actions/checkout@v3
      
      - uses: https://github.com/docker/setup-buildx-action@v2

      - uses: https://github.com/docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - uses: https://github.com/docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.actor }}/${{ github.repository }}:latest
